### ISSUE TITLE
Validator version 1.16.13 assert at core/src/unprocessed_transaction_storage.rs:819:9

### ISSUE THREAD

**Issue by bji** [jito-foundation/jito-solana#373]
#### Problem
Validator running 1.16.13 JITO crashed about half an hour ago. Logs show this immediately preceeding the solana-validator process exit and systemctl restart of the service:

```
[2023-09-13T04:25:34.298200991Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=1i bank_slot=217248296i retried_txs_per_block_limit_count=0i retried_txs_per_vote_limit_count=0i r
etried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
thread 'solBanknStgTx03' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', core/src/unprocessed_transaction_storage.rs:819:9
stack backtrace:
[2023-09-13T04:25:34.311850899Z INFO  solana_metrics::metrics] datapoint: qos-service-stats id=2i bank_slot=217248296i compute_cost_time=233i compute_cost_count=668i cost_tracking_time=280i sele
cted_txs_count=615i estimated_signature_cu=442800i estimated_write_lock_cu=669300i estimated_data_bytes_cu=16977i estimated_builtins_execute_cu=52050i estimated_bpf_execute_cu=139820000i actual_
bpf_execute_cu=859870i actual_execute_time_us=11069i
[2023-09-13T04:25:34.311878121Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=2i bank_slot=217248296i retried_txs_per_block_limit_count=53i retried_txs_per_vote_limit_count=0i 
retried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
[2023-09-13T04:25:34.325990535Z INFO  solana_metrics::metrics] datapoint: qos-service-stats id=5i bank_slot=217248296i compute_cost_time=309i compute_cost_count=759i cost_tracking_time=264i sele
cted_txs_count=752i estimated_signature_cu=542160i estimated_write_lock_cu=856200i estimated_data_bytes_cu=18256i estimated_builtins_execute_cu=46950i estimated_bpf_execute_cu=186150000i actual_
bpf_execute_cu=2323406i actual_execute_time_us=26054i
[2023-09-13T04:25:34.326031883Z INFO  solana_metrics::metrics] datapoint: qos-service-errors id=5i bank_slot=217248296i retried_txs_per_block_limit_count=7i retried_txs_per_vote_limit_count=0i r
etried_txs_per_account_limit_count=0i retried_txs_per_account_data_block_limit_count=0i dropped_txs_per_account_data_total_limit_count=0i
   0: rust_begin_unwind
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
   4: solana_core::unprocessed_transaction_storage::UnprocessedTransactionStorage::process_packets
   5: solana_core::banking_stage::consumer::Consumer::consume_buffered_packets
   6: solana_core::banking_stage::BankingStage::process_loop
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-09-13T04:25:34.366116768Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBanknStgTx03" one=1i message="panicked at 'assertion failed: `(left == right)`
      left: `0`,
     right: `1`', core/src/unprocessed_transaction_storage.rs:819:9" location="core/src/unprocessed_transaction_storage.rs:819:9" version="1.16.13 (src:00000000; feat:3949673676, client:JitoLabs)"
```

**Comment by bji** [comment]
I have investigated the code and see that this assert is in a JITO modification to the Solana validator code base.

**Comment by bji** [comment]
[log.txt](https://github.com/jito-foundation/jito-solana/files/12593589/log.txt)

These are 10,000 validator log lines preceeding the "ArgsO" line of the restart.

**Comment by bji** [comment]
I was wrong - the code in question is from the stock Solana Labs code base, it's just that it moved in the JITO version because other code was added above it, and I got confused and thought it was a new function in the jito code; but it's not.

I will close this and re-open the Solana Labs issue.

**Comment by michaelh-laine** [comment]
[assert_panic_1.log](https://github.com/jito-foundation/jito-solana/files/12593770/assert_panic_1.log)
my logs, this has now been confirmed as jito related and isolated to 1.16.x

**Comment by bji** [comment]
Re-opened it since it is indeed a JITO issue.

**Comment by buffalu** [comment]
thanks. as hot patch, ive disabled the following accounts on the relayers, which shouldn't interfere with normal transactions. these are the tip program config PDA followed by the 8 tip accounts, which are the 8 blacklisted accounts mentioned in the tpu causing this issue
```
96gYZGLnJYVFmbjzopPSU6QiEV5fGqZNyN9nmNhvrZU5 HFqU5x63VTqvQss8hp11i4wVV8bD44PvwucfZ2bU7gRe Cw8CFyM9FkoMi7K7Crf6HNQqf4uEMzpKw6QNghXLvLkY ADaUMid9yfUytqMBgopwjb2DTLSokTSzL1zt6iGPaS49 DfXygSm4jCyNCybVYYK6DwvWqjKee8pbDmJGcLWNDXjh ADuUkR4vqLUMWXxW9gh6D6L8pMSawimctcNZ5pGwDcEt DttWaMuVvTiduZRnguLF7jNxTgiMBZ1hyAumKUiL2KRL 3AVi9Tg9Uo68tJfuvoKvqKNWKkC5wPdSSdeBnizKZ6jT HgzT81VF1xZ3FT9Eq1pHhea7Wcfq2bv4tWTP3VvJ8Y9D
```

fixes:
https://github.com/jito-foundation/jito-solana/pull/374
https://github.com/jito-foundation/jito-solana/pull/376
