### ISSUE TITLE
release v1.16.20-jito

### ISSUE THREAD

**Issue by MattKetmo** [jito-foundation/jito-solana#485]
Hello, 

Do you plan to release v1.16.20-jito ?

We had issue yesterday using v1.16.19-jito with a fresh downloaded snapshot. I had to switch to the (non-jito) v1.16.20 release to make it work.

Each snapshot we tested finished with this kind of panic:

```
thread 'main' panicked at 'Snapshot bank for slot 232831868 failed to verify', /solana/runtime/src/snapshot_utils.rs:1627:9
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: solana_runtime::snapshot_utils::bank_from_latest_snapshot_archives
   3: solana_ledger::bank_forks_utils::bank_forks_from_snapshot
   4: solana_ledger::bank_forks_utils::load_bank_forks
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-11-28T22:05:01.183338487Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank for slot 232831868 failed to verify', /solana/runtime/src/snapshot_utils.rs:1627:9" location="/solana/runtime/src/snapshot_utils.rs:1627:9" version="1.16.19 (src:00000000; feat:4033350765, client:JitoLabs)"
[2023-11-28T22:05:02.003073048Z INFO  solana_metrics::metrics] datapoint: accounts_db_active hash=1i
[2023-11-28T22:05:02.015604374Z INFO  solana_metrics::metrics] datapoint: net-stats-validator in_datagrams_delta=8i no_ports_delta=0i in_errors_delta=466i out_datagrams_delta=8i rcvbuf_errors_delta=466i sndbuf_errors_delta=0i in_csum_errors_delta=0i ignored_multi_delta=0i in_errors=2970962i rcvbuf_errors=2970962i sndbuf_errors=0i rx_bytes_delta=251694i rx_packets_delta=487i rx_errs_delta=0i rx_drops_delta=0i rx_fifo_delta=0i rx_frame_delta=0i tx_bytes_delta=7827i tx_packets_delta=22i tx_errs_delta=0i tx_drops_delta=0i tx_fifo_delta=0i tx_colls_delta=0i
```

Thanks

**Comment by MattKetmo** [comment]
solana v1.16.21 is now released (let's skip directly to that new one?) 😄
